/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ProcessoSeletivoRouteImport } from './routes/processo-seletivo'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumIdRouteImport } from './routes/forum.$id'
import { Route as ForumNovaRouteImport } from './routes/forum.nova'
import { Route as PaisesIndexRouteImport } from './routes/paises.index'
import { Route as PaisesIdRouteImport } from './routes/paises.$id'
import { Route as UniversidadesIndexRouteImport } from './routes/universidades.index'
import { Route as UniversidadesIdRouteImport } from './routes/universidades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoSeletivoRoute = ProcessoSeletivoRouteImport.update({
  id: '/processo-seletivo',
  path: '/processo-seletivo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNovaRoute = ForumNovaRouteImport.update({
  id: '/forum/nova',
  path: '/forum/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesIndexRoute = PaisesIndexRouteImport.update({
  id: '/paises/',
  path: '/paises/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesIdRoute = PaisesIdRouteImport.update({
  id: '/paises/$id',
  path: '/paises/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversidadesIndexRoute = UniversidadesIndexRouteImport.update({
  id: '/universidades/',
  path: '/universidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversidadesIdRoute = UniversidadesIdRouteImport.update({
  id: '/universidades/$id',
  path: '/universidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatos': typeof ContatosRoute
  '/processo-seletivo': typeof ProcessoSeletivoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/nova': typeof ForumNovaRoute
  '/paises/$id': typeof PaisesIdRoute
  '/universidades/$id': typeof UniversidadesIdRoute
  '/forum/': typeof ForumIndexRoute
  '/paises/': typeof PaisesIndexRoute
  '/universidades/': typeof UniversidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatos': typeof ContatosRoute
  '/processo-seletivo': typeof ProcessoSeletivoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/nova': typeof ForumNovaRoute
  '/paises/$id': typeof PaisesIdRoute
  '/universidades/$id': typeof UniversidadesIdRoute
  '/forum': typeof ForumIndexRoute
  '/paises': typeof PaisesIndexRoute
  '/universidades': typeof UniversidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatos': typeof ContatosRoute
  '/processo-seletivo': typeof ProcessoSeletivoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/nova': typeof ForumNovaRoute
  '/paises/$id': typeof PaisesIdRoute
  '/universidades/$id': typeof UniversidadesIdRoute
  '/forum/': typeof ForumIndexRoute
  '/paises/': typeof PaisesIndexRoute
  '/universidades/': typeof UniversidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contatos'
    | '/processo-seletivo'
    | '/quem-somos'
    | '/forum/$id'
    | '/forum/nova'
    | '/paises/$id'
    | '/universidades/$id'
    | '/forum/'
    | '/paises/'
    | '/universidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatos'
    | '/processo-seletivo'
    | '/quem-somos'
    | '/forum/$id'
    | '/forum/nova'
    | '/paises/$id'
    | '/universidades/$id'
    | '/forum'
    | '/paises'
    | '/universidades'
  id:
    | '__root__'
    | '/'
    | '/contatos'
    | '/processo-seletivo'
    | '/quem-somos'
    | '/forum/$id'
    | '/forum/nova'
    | '/paises/$id'
    | '/universidades/$id'
    | '/forum/'
    | '/paises/'
    | '/universidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatosRoute: typeof ContatosRoute
  ProcessoSeletivoRoute: typeof ProcessoSeletivoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ForumIdRoute: typeof ForumIdRoute
  ForumNovaRoute: typeof ForumNovaRoute
  PaisesIdRoute: typeof PaisesIdRoute
  UniversidadesIdRoute: typeof UniversidadesIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
  PaisesIndexRoute: typeof PaisesIndexRoute
  UniversidadesIndexRoute: typeof UniversidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo-seletivo': {
      id: '/processo-seletivo'
      path: '/processo-seletivo'
      fullPath: '/processo-seletivo'
      preLoaderRoute: typeof ProcessoSeletivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/nova': {
      id: '/forum/nova'
      path: '/forum/nova'
      fullPath: '/forum/nova'
      preLoaderRoute: typeof ForumNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises/': {
      id: '/paises/'
      path: '/paises'
      fullPath: '/paises/'
      preLoaderRoute: typeof PaisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises/$id': {
      id: '/paises/$id'
      path: '/paises/$id'
      fullPath: '/paises/$id'
      preLoaderRoute: typeof PaisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidades/': {
      id: '/universidades/'
      path: '/universidades'
      fullPath: '/universidades/'
      preLoaderRoute: typeof UniversidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidades/$id': {
      id: '/universidades/$id'
      path: '/universidades/$id'
      fullPath: '/universidades/$id'
      preLoaderRoute: typeof UniversidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatosRoute: ContatosRoute,
  ProcessoSeletivoRoute: ProcessoSeletivoRoute,
  QuemSomosRoute: QuemSomosRoute,
  ForumIdRoute: ForumIdRoute,
  ForumNovaRoute: ForumNovaRoute,
  PaisesIdRoute: PaisesIdRoute,
  UniversidadesIdRoute: UniversidadesIdRoute,
  ForumIndexRoute: ForumIndexRoute,
  PaisesIndexRoute: PaisesIndexRoute,
  UniversidadesIndexRoute: UniversidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
